---
- hosts: all
  gather_facts: no
  pre_tasks:
    - name: 'install python2'
      raw: sudo apt-get -y install python-simplejson
  vars_files:
    - '../vars/{{ env }}.yml'
  roles:
    - { role: './roles/install-docker' }
    - { role: './roles/mysql' }
    - { role: './roles/wordpress' }
    - { role: './roles/nginx' }
    - { role: './roles/awscli' }
    - { role: './roles/frontend' }
