---
- name: apt update
  apt: update_cache=yes

- name: check that nginx was installed
  apt: name=nginx state=present

- name: Create conf.d directory
  file: path=/etc/nginx/conf.d state=directory

- name: Create sites-enabled directory
  file: path=/etc/nginx/sites-enabled state=directory

- name: Create logs directory
  file: path=/etc/nginx/logs state=directory

- name: Create nginx.conf file from template
  template:
    src: "{{ role_path }}/files/nginx.conf"
    dest: /etc/nginx/nginx.conf

- name: stop nginx
  service:
    name: nginx
    state: stopped
  ignore_errors: yes
  become: true
  become_user: root
  become_method: sudo
  
- name: start nginx
  service:
    name: nginx
    state: started
  become: true
  become_user: root
  become_method: sudo

