---
- name: check if docker is installed
  command: command -v docker
  ignore_errors: yes
  register: docker_installed

- name: add docker apt keyserver
  command: apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
  when: docker_installed is failed

- name: add deb repo
  command: sudo touch /etc/apt/sources.list.d/docker.list

- lineinfile: dest="/etc/apt/sources.list.d/docker.list" line="{{ item }}"
  with_items:
    - "deb https://apt.dockerproject.org/repo ubuntu-{{ ubuntu_version_name }} main"

- name: apt update
  apt: update_cache=yes

- name: check that docker engine was installed
  apt: name=docker-engine state=present
