- name: apt update
  apt: update_cache=yes

- name: check that awscli dependencies are installed
  apt: name={{ item }} state=present
  with_items:
    - python
    - python-pip

- name: install awscli using pip
  pip:
    name: awscli
    state: present
    extra_args: "--upgrade"
    executable: /usr/bin/pip
